"""
Report Generation Module
Creates human-readable analysis reports with actionable insights
"""

from typing import Dict, List, Any
from datetime import datetime
from collections import defaultdict
import json


class ReportGenerator:
    """Generates comprehensive analysis reports"""
    
    def __init__(self):
        self.report_template = """
# API Log Analysis Report

**Generated:** {timestamp}
**Severity Level:** {severity}

## Executive Summary
{summary}

## Key Findings

### 🔴 Errors Detected
{errors_section}

### ⚠️ Warnings
{warnings_section}

### 📊 Pattern Analysis
{patterns_section}

### 📈 Trends
{trends_section}

### 🎯 Early Warning Signs
{early_signs_section}

## Detailed Analysis

### Error Categories
{error_categories}

### Timeline of Events
{timeline}

### Anomalies Detected
{anomalies}

## Recommendations
{recommendations}

## Action Items
{action_items}

## Historical Context
{historical_context}

---
*This report was automatically generated by the API Log Monitoring Agent*
"""
    
    def generate(self, analysis: Dict, error_history: List, error_patterns: Dict) -> str:
        """Generate a comprehensive report from analysis data"""
        
        report_data = {
            'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'severity': self._format_severity(analysis['severity']),
            'summary': self._generate_summary(analysis),
            'errors_section': self._format_errors(analysis.get('errors', [])),
            'warnings_section': self._format_warnings(analysis.get('warnings', [])),
            'patterns_section': self._format_patterns(analysis.get('patterns', {})),
            'trends_section': self._format_trends(analysis.get('patterns', {}).get('trends', {})),
            'early_signs_section': self._format_early_signs(analysis.get('early_signs', [])),
            'error_categories': self._format_error_categories(analysis.get('errors', [])),
            'timeline': self._generate_timeline(analysis),
            'anomalies': self._format_anomalies(analysis.get('patterns', {}).get('anomalies', [])),
            'recommendations': self._format_recommendations(analysis.get('recommendations', [])),
            'action_items': self._generate_action_items(analysis),
            'historical_context': self._format_historical_context(error_history, error_patterns)
        }
        
        return self.report_template.format(**report_data)
    
    def _format_severity(self, severity: str) -> str:
        """Format severity with emoji indicator"""
        severity_map = {
            'critical': '🔴 CRITICAL',
            'high': '🟠 HIGH',
            'medium': '🟡 MEDIUM',
            'low': '🟢 LOW',
            'normal': '✅ NORMAL'
        }
        return severity_map.get(severity, severity.upper())
    
    def _generate_summary(self, analysis: Dict) -> str:
        """Generate executive summary"""
        errors = analysis.get('errors', [])
        warnings = analysis.get('warnings', [])
        early_signs = analysis.get('early_signs', [])
        
        summary_parts = []
        
        if analysis['severity'] in ['critical', 'high']:
            summary_parts.append("⚠️ **Immediate attention required!**")
        
        if errors:
            summary_parts.append(f"- Detected **{len(errors)} errors** in recent logs")
        
        if warnings:
            summary_parts.append(f"- Found **{len(warnings)} warnings** that may indicate emerging issues")
        
        if early_signs:
            summary_parts.append(f"- Identified **{len(early_signs)} early warning patterns**")
        
        trends = analysis.get('patterns', {}).get('trends', {})
        if trends.get('increasing_errors'):
            summary_parts.append("- ⚠️ **Error rate is increasing**")
        
        if not summary_parts:
            summary_parts.append("System appears to be operating normally with no significant issues detected.")
        
        return '\n'.join(summary_parts)
    
    def _format_errors(self, errors: List[Dict]) -> str:
        """Format errors section"""
        if not errors:
            return "*No errors detected in the analyzed period.*"
        
        # Group errors by severity
        by_severity = defaultdict(list)
        for error in errors:
            by_severity[error.get('severity', 'unknown')].append(error)
        
        sections = []
        
        for severity in ['critical', 'high', 'medium']:
            if severity in by_severity:
                sections.append(f"\n**{severity.upper()} Priority:**")
                for error in by_severity[severity][:5]:  # Show top 5
                    desc = error.get('description', 'Unknown error')
                    line = error.get('line_number', '?')
                    sections.append(f"- Line {line}: {desc}")
                    if error.get('details', {}).get('error_message'):
                        sections.append(f"  - Message: `{error['details']['error_message'][:100]}`")
        
        return '\n'.join(sections) if sections else "*No significant errors found.*"
    
    def _format_warnings(self, warnings: List[Dict]) -> str:
        """Format warnings section"""
        if not warnings:
            return "*No warnings detected.*"
        
        sections = []
        
        # Group similar warnings
        warning_groups = defaultdict(list)
        for warning in warnings:
            key = warning.get('description', 'Unknown')
            warning_groups[key].append(warning)
        
        for desc, group in list(warning_groups.items())[:5]:
            sections.append(f"- **{desc}**: {len(group)} occurrence(s)")
            if len(group) == 1:
                sections.append(f"  - Line {group[0].get('line_number', '?')}")
            else:
                lines = [str(w.get('line_number', '?')) for w in group[:3]]
                sections.append(f"  - Lines: {', '.join(lines)}...")
        
        return '\n'.join(sections)
    
    def _format_patterns(self, patterns: Dict) -> str:
        """Format pattern analysis section"""
        if not patterns:
            return "*No patterns analyzed.*"
        
        sections = []
        
        # Error clusters
        clusters = patterns.get('error_clusters', [])
        if clusters:
            sections.append("\n**Error Clustering:**")
            for cluster in clusters[:3]:
                sections.append(f"- Lines {cluster['start_line']}-{cluster['end_line']}: "
                              f"{cluster['error_count']} errors clustered together")
        
        # Key patterns detected
        pattern_counts = {}
        for pattern_name, matches in patterns.items():
            if pattern_name not in ['error_clusters', 'trends', 'anomalies'] and matches:
                pattern_counts[pattern_name] = len(matches)
        
        if pattern_counts:
            sections.append("\n**Detected Patterns:**")
            for pattern, count in sorted(pattern_counts.items(), key=lambda x: x[1], reverse=True)[:5]:
                pattern_display = pattern.replace('_', ' ').title()
                sections.append(f"- {pattern_display}: {count} occurrence(s)")
        
        return '\n'.join(sections) if sections else "*No significant patterns detected.*"
    
    def _format_trends(self, trends: Dict) -> str:
        """Format trends section"""
        if not trends:
            return "*No trend data available.*"
        
        sections = []
        
        if trends.get('increasing_errors'):
            velocity = trends.get('error_velocity', 0)
            sections.append(f"⚠️ **Error rate increasing** (velocity: +{velocity:.1f} errors/window)")
        
        repeated = trends.get('repeated_patterns', [])
        if repeated:
            sections.append("\n**Repeated Error Patterns:**")
            for msg, count in repeated[:3]:
                sections.append(f"- `{msg[:80]}...` ({count} times)")
        
        common_terms = trends.get('common_terms', [])
        if common_terms:
            terms = [term for term, _ in common_terms[:5]]
            sections.append(f"\n**Frequently appearing terms:** {', '.join(terms)}")
        
        return '\n'.join(sections) if sections else "*No significant trends detected.*"
    
    def _format_early_signs(self, early_signs: List[Dict]) -> str:
        """Format early warning signs"""
        if not early_signs:
            return "*No early warning signs detected.*"
        
        sections = []
        
        for sign in early_signs:
            pattern = sign['pattern'].replace('_', ' ').title()
            count = sign['count']
            
            if count > 10:
                emoji = "🔴"
            elif count > 5:
                emoji = "🟠"
            else:
                emoji = "🟡"
            
            sections.append(f"{emoji} **{pattern}**: {count} occurrence(s)")
        
        return '\n'.join(sections)
    
    def _format_error_categories(self, errors: List[Dict]) -> str:
        """Categorize and format errors"""
        if not errors:
            return "*No errors to categorize.*"
        
        categories = defaultdict(int)
        
        for error in errors:
            line = error.get('raw_line', '').lower()
            
            if 'database' in line or 'sql' in line:
                categories['Database'] += 1
            elif 'connection' in line or 'network' in line:
                categories['Network'] += 1
            elif 'auth' in line or 'permission' in line:
                categories['Authentication'] += 1
            elif 'timeout' in line:
                categories['Timeout'] += 1
            else:
                categories['Application'] += 1
        
        sections = []
        for category, count in sorted(categories.items(), key=lambda x: x[1], reverse=True):
            sections.append(f"- **{category}**: {count} error(s)")
        
        return '\n'.join(sections)
    
    def _generate_timeline(self, analysis: Dict) -> str:
        """Generate timeline of events"""
        events = []
        
        # Add errors with timestamps
        for error in analysis.get('errors', [])[:5]:
            if error.get('timestamp'):
                events.append(f"- {error['timestamp']}: {error.get('description', 'Error')}")
        
        if not events:
            return "*No timestamped events available.*"
        
        return '\n'.join(events)
    
    def _format_anomalies(self, anomalies: List[Dict]) -> str:
        """Format detected anomalies"""
        if not anomalies:
            return "*No anomalies detected.*"
        
        sections = []
        
        for anomaly in anomalies[:5]:
            anomaly_type = anomaly['type'].replace('_', ' ').title()
            sections.append(f"- **{anomaly_type}** at line {anomaly['line_number']}")
            sections.append(f"  - {anomaly['description']}")
        
        return '\n'.join(sections)
    
    def _format_recommendations(self, recommendations: List[str]) -> str:
        """Format recommendations"""
        if not recommendations:
            return "*No specific recommendations at this time.*"
        
        sections = []
        for i, rec in enumerate(recommendations, 1):
            sections.append(f"{i}. {rec}")
        
        return '\n'.join(sections)
    
    def _generate_action_items(self, analysis: Dict) -> str:
        """Generate prioritized action items"""
        action_items = []
        
        severity = analysis.get('severity', 'normal')
        
        if severity == 'critical':
            action_items.append("🔴 **IMMEDIATE**: Investigate critical errors and implement fixes")
            action_items.append("🔴 **IMMEDIATE**: Check system health and dependent services")
        elif severity == 'high':
            action_items.append("🟠 **HIGH**: Review error logs and identify root cause")
            action_items.append("🟠 **HIGH**: Monitor system closely for degradation")
        
        if analysis.get('patterns', {}).get('trends', {}).get('increasing_errors'):
            action_items.append("⚠️ **IMPORTANT**: Investigate increasing error trend")
        
        early_signs = analysis.get('early_signs', [])
        if any(sign['count'] > 10 for sign in early_signs):
            action_items.append("⚠️ **IMPORTANT**: Address frequently occurring warning patterns")
        
        if not action_items:
            action_items.append("✅ Continue monitoring for changes")
            action_items.append("✅ Review logs periodically for emerging patterns")
        
        return '\n'.join(action_items)
    
    def _format_historical_context(self, error_history: List, error_patterns: Dict) -> str:
        """Format historical context"""
        sections = []
        
        if error_history:
            recent_errors = sum(1 for event in error_history[-10:] 
                              if event.get('error_count', 0) > 0)
            sections.append(f"- Recent history: {recent_errors} error events in last 10 checks")
        
        if error_patterns:
            top_patterns = sorted(error_patterns.items(), key=lambda x: x[1], reverse=True)[:3]
            if top_patterns:
                sections.append("\n**Most frequent patterns:**")
                for pattern, count in top_patterns:
                    sections.append(f"- {pattern}: {count} occurrences")
        
        return '\n'.join(sections) if sections else "*No historical data available.*"