#!/bin/bash

# Simple API Log Monitor
# Direct Docker-based monitoring without Python complexity

set -e

# Configuration
LOG_LINES=${LOG_LINES:-500}
CHECK_INTERVAL=${CHECK_INTERVAL:-30}
COMPOSE_FILE=${COMPOSE_FILE:-"../../docker-compose.dev.yml"}
CONTAINER=${CONTAINER:-"api"}
REPORT_DIR="./reports"
STATE_DIR="./state"

# Colors for output
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Create directories if they don't exist
mkdir -p "$REPORT_DIR" "$STATE_DIR"

# Function to fetch and analyze logs
analyze_logs() {
    echo "🔍 Fetching last $LOG_LINES lines from $CONTAINER..."
    
    # Fetch logs
    LOGS=$(docker-compose -f "$COMPOSE_FILE" logs --tail="$LOG_LINES" "$CONTAINER" 2>&1)
    
    # Count different types of issues
    CRITICAL_COUNT=$(echo "$LOGS" | grep -ciE "CRITICAL|FATAL|PANIC" || true)
    ERROR_COUNT=$(echo "$LOGS" | grep -ciE "ERROR\s+-\s+|Exception:|Traceback" || true)
    WARNING_COUNT=$(echo "$LOGS" | grep -ciE "WARNING\s+-\s+" || true)
    TIMEOUT_COUNT=$(echo "$LOGS" | grep -ciE "timeout|timed out" || true)
    RATE_LIMIT_COUNT=$(echo "$LOGS" | grep -ciE "rate.?limit|429" || true)
    HTTP_ERROR_COUNT=$(echo "$LOGS" | grep -cE "\"code\":\s*(4[0-9]{2}|5[0-9]{2})" || true)
    
    # Determine severity
    SEVERITY="NORMAL"
    SEVERITY_COLOR="$GREEN"
    
    if [ "$CRITICAL_COUNT" -gt 0 ]; then
        SEVERITY="CRITICAL"
        SEVERITY_COLOR="$RED"
    elif [ "$ERROR_COUNT" -gt 10 ]; then
        SEVERITY="HIGH"
        SEVERITY_COLOR="$RED"
    elif [ "$ERROR_COUNT" -gt 5 ] || [ "$HTTP_ERROR_COUNT" -gt 5 ]; then
        SEVERITY="MEDIUM"
        SEVERITY_COLOR="$YELLOW"
    elif [ "$WARNING_COUNT" -gt 5 ] || [ "$TIMEOUT_COUNT" -gt 3 ]; then
        SEVERITY="LOW"
        SEVERITY_COLOR="$YELLOW"
    fi
    
    # Display summary
    echo -e "\n📊 Analysis Summary"
    echo "==================="
    echo -e "Severity: ${SEVERITY_COLOR}${SEVERITY}${NC}"
    echo "Critical Issues: $CRITICAL_COUNT"
    echo "Errors: $ERROR_COUNT"
    echo "Warnings: $WARNING_COUNT"
    echo "Timeouts: $TIMEOUT_COUNT"
    echo "Rate Limits: $RATE_LIMIT_COUNT"
    echo "HTTP Errors: $HTTP_ERROR_COUNT"
    
    # Generate report if needed
    if [ "$SEVERITY" != "NORMAL" ] && [ "$SEVERITY" != "LOW" ]; then
        generate_report "$LOGS" "$SEVERITY"
    fi
    
    # Save state
    echo "{
        \"last_check\": \"$(date -Iseconds)\",
        \"severity\": \"$SEVERITY\",
        \"error_count\": $ERROR_COUNT,
        \"warning_count\": $WARNING_COUNT
    }" > "$STATE_DIR/last_check.json"
}

# Function to generate a detailed report
generate_report() {
    local LOGS="$1"
    local SEVERITY="$2"
    local TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    local REPORT_FILE="$REPORT_DIR/report_${TIMESTAMP}.md"
    
    echo -e "\n📝 Generating report: $REPORT_FILE"
    
    cat > "$REPORT_FILE" << EOF
# API Log Analysis Report

**Generated:** $(date '+%Y-%m-%d %H:%M:%S')
**Severity:** $SEVERITY

## Summary

- Critical Issues: $CRITICAL_COUNT
- Errors: $ERROR_COUNT  
- Warnings: $WARNING_COUNT
- Timeouts: $TIMEOUT_COUNT
- Rate Limits: $RATE_LIMIT_COUNT
- HTTP Errors: $HTTP_ERROR_COUNT

## Error Samples

### Critical Errors
\`\`\`
$(echo "$LOGS" | grep -iE "CRITICAL|FATAL|PANIC" | head -5 || echo "None found")
\`\`\`

### Application Errors
\`\`\`
$(echo "$LOGS" | grep -E "ERROR\s+-\s+" | head -10 || echo "None found")
\`\`\`

### Warnings
\`\`\`
$(echo "$LOGS" | grep -E "WARNING\s+-\s+" | head -5 || echo "None found")
\`\`\`

### Timeouts
\`\`\`
$(echo "$LOGS" | grep -iE "timeout|timed out" | head -5 || echo "None found")
\`\`\`

### HTTP Errors
\`\`\`
$(echo "$LOGS" | grep -E "\"code\":\s*(4[0-9]{2}|5[0-9]{2})" | head -5 || echo "None found")
\`\`\`

## Recommendations

$(generate_recommendations)

---
*Report generated by Simple API Monitor*
EOF
    
    echo -e "${GREEN}✅ Report saved${NC}"
}

# Function to generate recommendations
generate_recommendations() {
    local RECS=""
    
    if [ "$CRITICAL_COUNT" -gt 0 ]; then
        RECS="${RECS}- **IMMEDIATE ACTION REQUIRED**: Critical errors detected\n"
    fi
    
    if [ "$ERROR_COUNT" -gt 10 ]; then
        RECS="${RECS}- High error rate detected - investigate root cause\n"
    fi
    
    if [ "$TIMEOUT_COUNT" -gt 5 ]; then
        RECS="${RECS}- Multiple timeouts detected - check service performance\n"
    fi
    
    if [ "$RATE_LIMIT_COUNT" -gt 0 ]; then
        RECS="${RECS}- Rate limiting detected - consider request throttling\n"
    fi
    
    if [ "$HTTP_ERROR_COUNT" -gt 5 ]; then
        RECS="${RECS}- High HTTP error rate - check API endpoints\n"
    fi
    
    if [ -z "$RECS" ]; then
        RECS="- System appears healthy - continue monitoring"
    fi
    
    echo -e "$RECS"
}

# Function for continuous monitoring
continuous_monitor() {
    echo "🚀 Starting continuous monitoring (interval: ${CHECK_INTERVAL}s)"
    echo "Press Ctrl+C to stop"
    
    while true; do
        echo -e "\n📅 Check at $(date '+%Y-%m-%d %H:%M:%S')"
        echo "----------------------------------------"
        analyze_logs
        echo -e "\n💤 Sleeping for ${CHECK_INTERVAL} seconds..."
        sleep "$CHECK_INTERVAL"
    done
}

# Main execution
case "${1:-}" in
    once)
        analyze_logs
        ;;
    continuous)
        continuous_monitor
        ;;
    report)
        # Force generate a report
        analyze_logs
        LOGS=$(docker-compose -f "$COMPOSE_FILE" logs --tail="$LOG_LINES" "$CONTAINER" 2>&1)
        generate_report "$LOGS" "MANUAL"
        ;;
    *)
        echo "Usage: $0 {once|continuous|report}"
        echo ""
        echo "  once       - Run single analysis"
        echo "  continuous - Run continuous monitoring"  
        echo "  report     - Generate immediate report"
        echo ""
        echo "Environment variables:"
        echo "  LOG_LINES=${LOG_LINES} - Number of log lines to analyze"
        echo "  CHECK_INTERVAL=${CHECK_INTERVAL} - Seconds between checks"
        echo "  COMPOSE_FILE=${COMPOSE_FILE} - Path to docker-compose file"
        echo "  CONTAINER=${CONTAINER} - Container name to monitor"
        exit 1
        ;;
esac